# default set of lint rules enforced for projects at Google
# https://github.com/dart-lang/pedantic#enabled-lints
include: package:pedantic/analysis_options.yaml

# http://dart-lang.github.io/linter/lints
linter:
  rules:
    omit_local_variable_types: false
    unnecessary_this: false
    await_only_futures: true

analyzer:
#   exclude:
#     - path/to/excluded/files/**

