name: stack_blur
description: "Fast and beautiful image blurring algorithm for raw RGBA pixel buffers."
version: 0.2.2
homepage: https://github.com/rtmigo/stack_blur_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # none

dev_dependencies:
  test: ^1.5.1
  lints: ^1.0.0
  image: ^3.1.0

