# https://github.com/dart-lang/setup-dart

name: unittest

on:
  push:
    branches: [master]
    paths-ignore:
      - 'example/*'
      - '**.md'
      - '**.txt'

  pull_request:
    branches: [master]
    paths-ignore:
      - 'example/*'
      - '**.md'
      - '**.txt'

jobs:
  test:
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] # [ubuntu-latest, macos-latest, windows-latest]
        sdk: [2.12.0] # dart is null-safe since 2.12
        #platform: [node, vm, chrome]
        #sdk: [stable, beta, dev, 2.12.0-29.10.beta]
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Tests
        run: dart test

